### ISSUE TITLE
aswg not login

### ISSUE THREAD

**Issue by PsychoMantis991** [Aquerr/ARMA-Server-Web-Gui#18]
Good afternoon,

When I try to log in to the website, I always get the same error, even after modifying the .properties file.
![image](https://github.com/user-attachments/assets/ccc3decc-058b-4183-92f9-184e77c6e74d)

Regards

**Comment by Aquerr** [comment]
Strange, have you tried debugging what errors do you have in your backend logs?

**Comment by Aquerr** [comment]
Strange, have you tried debugging what errors do you have in your backend logs?

**Comment by Aquerr** [comment]
I updated the installation (and build) instruction in README.md.

**Comment by PsychoMantis991** [comment]
Hi again,

I have tried again, following the steps indicated and when loading the website, the following message appears.
![image](https://github.com/user-attachments/assets/507be5d8-e6aa-438c-a4d5-5ac04f9583a2)

In the log, the following is shown.
![image](https://github.com/user-attachments/assets/4508908f-6e96-459c-a26c-aeec2f28281a)

After changing the default user and password and trying to log in, the log tells me the following.
![image](https://github.com/user-attachments/assets/4d9e50f5-8e20-4f05-8d96-c02aa8422885)

I'm testing on a virtual machine and instead of using the domain name or localhost, I'm using the server's IP. I'm sending you a screenshot of the .properties file and the environment.prod.ts file.
![image](https://github.com/user-attachments/assets/c637e606-c27e-4052-91bd-97ee50a4bacf)
![image](https://github.com/user-attachments/assets/656883fc-541e-4e83-93f0-a668c501502f)

I'm using ubuntu server 24.04

Best regards.
